
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: kU#m5eHY5iTiQj#q
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?useUnicode=true&amp;characterEncoding=UTF-8&amp;useSSL=false
  jpa:
    show-sql: true
server:
  port: 8081
  
env: dev-test

# 自定义规则
PRODUCT:
  ribbon:
    NFLoadBalancerClassName: com.netflix.loadbalancer.RandomRule
